name: optima
description: "Optimized outreach, maximum success."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2





dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^2.6.0
  flutter_native_splash: ^2.3.9
  particles_flutter: ^0.1.3

  firebase_core: ^2.25.3
  firebase_auth: ^4.17.4
  google_sign_in: ^6.3.0

  url_launcher: ^6.3.1

  lucide_icons: ^0.257.0

  http: ^1.3.0
  livekit_client: ^2.2.0
  record: ^6.0.0
  audioplayers: ^5.2.1
  permission_handler: ^11.0.1

  speech_to_text: 7.0.0
  flutter_volume_controller: ^1.2.0

  fl_chart: ^0.65.0

  image_picker: ^1.0.4
  crop_your_image: ^1.0.6
  flutter_image_compress: ^2.2.0

  dropdown_button2: ^2.3.9

  table_calendar: ^3.0.9
  flutter_time_picker_spinner: ^2.0.0
  flutter_map_location_picker: ^0.0.4
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.0
  firebase_app_check: ^0.2.0+1
  shared_preferences: ^2.2.2

  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2

  google_mobile_ads: ^5.0.0

  geolocator: ^11.0.0
  geocoding: ^2.1.0

  connectivity_plus: ^6.0.3
  path_provider: any

  provider: ^6.1.1
  device_preview: ^1.1.0
  animated_text_kit: ^4.2.2







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3




dependency_overrides:
  web: ^0.5.0
  flutter_webrtc: ^0.13.1+hotfix.1




flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo/logo_og.png"
  adaptive_icon_foreground: "assets/images/logo/logo_foreground.png"
  adaptive_icon_background: "assets/images/logo/logo_background.png"
  android_adaptive_icon_monochrome: "assets/images/logo/logo_foreground_monochrome_white.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/tutorials/
    - assets/splash/
    - assets/audio/intro/
    - assets/audio/wake/

    - assets/audio/actions/navigate/dashboard/
    - assets/audio/actions/navigate/events/
    - assets/audio/actions/navigate/settings/
    - assets/audio/actions/navigate/menu/

    - assets/audio/actions/change_setting/change_theme/
    - assets/audio/actions/change_setting/disable_jamie/
    - assets/audio/actions/change_setting/toggle_theme/
    - assets/audio/actions/change_setting/toggle_location/
    - assets/audio/actions/change_setting/toggle_notifications/
    - assets/audio/actions/change_setting/toggle_wakeword/
    - assets/audio/actions/change_setting/toggle_reminders/

    - assets/audio/actions/tap_widget/events/add_event/
    - assets/audio/actions/tap_widget/settings/show_credits/
    - assets/audio/actions/tap_widget/settings/show_sessions/
    - assets/audio/actions/tap_widget/dashboard/show_notifications/


    - assets/audio/credits/no_credits/
    - assets/audio/walk_through/

  fonts:
    - family: Tusker
      fonts:
        - asset: assets/fonts/tusker-grotesk-5500-medium.ttf








# dart run flutter_native_splash:create

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#ffcd32"
  color_dark: "#000000"
  image: assets/splash/empty.png

  android_12:
    # because we fuck android, why do you exist ðŸ˜­
    color: "#ffcd32"
    color_dark: "#000000"
    image: assets/splash/empty.png

